require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stadia", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Stadium. As you add validations to Stadium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Stadium.create! valid_attributes
      get stadia_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stadium = Stadium.create! valid_attributes
      get stadium_url(stadium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stadium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stadium = Stadium.create! valid_attributes
      get edit_stadium_url(stadium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stadium" do
        expect {
          post stadia_url, params: { stadium: valid_attributes }
        }.to change(Stadium, :count).by(1)
      end

      it "redirects to the created stadium" do
        post stadia_url, params: { stadium: valid_attributes }
        expect(response).to redirect_to(stadium_url(Stadium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Stadium" do
        expect {
          post stadia_url, params: { stadium: invalid_attributes }
        }.to change(Stadium, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post stadia_url, params: { stadium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stadium" do
        stadium = Stadium.create! valid_attributes
        patch stadium_url(stadium), params: { stadium: new_attributes }
        stadium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stadium" do
        stadium = Stadium.create! valid_attributes
        patch stadium_url(stadium), params: { stadium: new_attributes }
        stadium.reload
        expect(response).to redirect_to(stadium_url(stadium))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        stadium = Stadium.create! valid_attributes
        patch stadium_url(stadium), params: { stadium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stadium" do
      stadium = Stadium.create! valid_attributes
      expect {
        delete stadium_url(stadium)
      }.to change(Stadium, :count).by(-1)
    end

    it "redirects to the stadia list" do
      stadium = Stadium.create! valid_attributes
      delete stadium_url(stadium)
      expect(response).to redirect_to(stadia_url)
    end
  end
end
